### ISSUE TITLE
Windows package installation not working

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-python#72]
I think there are a couple of issues.

1) `apertium-en-es` isn't getting installed by `pip install apertium` (maybe nothing is since the below stack trace shows that wrappers were unavailable)
2) Installing a package requires restarting the interpreter??
3) Even then, I can't translate. Maybe some issue with paths?

This is on Win 10 inside cygwin.

```
>>> apertium.install_module('en-es')
[2019-09-03 02:33:33,339] {C:\Python37\lib\site-packages\apertium\installer.py:29} INFO - apertium-en-es download completed
[2019-09-03 02:33:33,554] {C:\Python37\lib\site-packages\apertium\installer.py:34} INFO - apertium-en-es Extraction completed
[2019-09-03 02:33:33,555] {C:\Python37\lib\site-packages\apertium\installer.py:36} INFO - apertium-en-es removed
[2019-09-03 02:33:33,555] {C:\Python37\lib\site-packages\apertium\installer.py:48} INFO - Copying Language Data to Apertium
[2019-09-03 02:33:33,748] {C:\Python37\lib\site-packages\apertium\installer.py:53} INFO - C:\cygwin64\tmp\tmpbqmc42hk\usr\share\apertium\apertium-eng-spa -> C:\Users\Susha\AppData\Local\apertium-all-dev\share\apertium\apertium-eng-spa
[2019-09-03 02:33:33,754] {C:\Python37\lib\site-packages\apertium\installer.py:53} INFO - C:\cygwin64\tmp\tmpbqmc42hk\usr\share\apertium\modes -> C:\Users\Susha\AppData\Local\apertium-all-dev\share\apertium\modes
[2019-09-03 02:33:33,761] {C:\Python37\lib\site-packages\apertium\installer.py:68} INFO - Editing mode eng-spa.mode
[2019-09-03 02:33:33,770] {C:\Python37\lib\site-packages\apertium\installer.py:68} INFO - Editing mode spa-eng.mode
[2019-09-03 02:33:33,779] {C:\Python37\lib\site-packages\apertium\installer.py:68} INFO - Editing mode spa-eng_US.mode
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 161, in translate
    raise apertium.ModeNotInstalled()
apertium.ModeNotInstalled
>>> exit()

Susha@Jacinth /cygdrive/c/Users/Susha
$ python3
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import apertium
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 168, in translate
    deformatted = self._get_deformat(str(deformater), text)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 118, in _get_deformat
    proc_deformat = Popen(deformat, stdin=PIPE, stdout=PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Vaydheesh** [comment]
do you also get the following output
```python
>>> platform.system()
'CYGWIN_NT-10.0'
```

**Comment by sushain97** [comment]
```
Susha@Jacinth /cygdrive/c/Users/Susha
$ python3
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; platform.system()
'Windows'
```

**Comment by sushain97** [comment]
This still isn't working for me:

```
                                                                   Susha@Jacinth /cygdrive/c/Users/Susha
                                            $ pip install apertium                                                                                      Collecting apertium
  Downloading https://files.pythonhosted.org/packages/4d/bf/989a1a0d975bf2838bc2a1554afc068c0a66b394e7bae4398ed73ccf1bf8/apertium-0.2.0-py3-none-any.whl
Collecting apertium-streamparser==5.0.2 (from apertium)
  Using cached https://files.pythonhosted.org/packages/ca/47/85027843345b1d7e4d0beca98c3c55ac8bb1b2d9069a126877b645be481c/apertium_streamparser-5.0.2-py3-none-any.whl
Installing collected packages: apertium-streamparser, apertium
Successfully installed apertium-0.2.0 apertium-streamparser-5.0.2
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
                                                                                                            Susha@Jacinth /cygdrive/c/Users/Susha
                                            $ python3                                                                                                   Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import apertium
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 168, in translate
    deformatted = self._get_deformat(str(deformater), text)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 118, in _get_deformat
    proc_deformat = Popen(deformat, stdin=PIPE, stdout=PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>> apertium.install_module('en-es')
[2019-09-06 04:56:17,876] {C:\Python37\lib\site-packages\apertium\installer.py:31} INFO - http://apertium.projectjj.com/win32/nightly/data.php?zip=apertium-en-es -> apertium-en-es download completed
[2019-09-06 04:56:18,094] {C:\Python37\lib\site-packages\apertium\installer.py:36} INFO - apertium-en-es Extraction completed
[2019-09-06 04:56:18,095] {C:\Python37\lib\site-packages\apertium\installer.py:38} INFO - apertium-en-es removed
[2019-09-06 04:56:18,095] {C:\Python37\lib\site-packages\apertium\installer.py:50} INFO - Copying Language Data to Apertium
[2019-09-06 04:56:18,282] {C:\Python37\lib\site-packages\apertium\installer.py:55} INFO - C:\cygwin64\tmp\tmpyru8_29k\usr\share\apertium\apertium-eng-spa -> C:\Users\Susha\AppData\Local\apertium-all-dev\share\apertium\apertium-eng-spa
[2019-09-06 04:56:18,294] {C:\Python37\lib\site-packages\apertium\installer.py:55} INFO - C:\cygwin64\tmp\tmpyru8_29k\usr\share\apertium\modes -> C:\Users\Susha\AppData\Local\apertium-all-dev\share\apertium\modes
[2019-09-06 04:56:18,301] {C:\Python37\lib\site-packages\apertium\installer.py:70} INFO - Editing mode eng-spa.mode
[2019-09-06 04:56:18,303] {C:\Python37\lib\site-packages\apertium\installer.py:70} INFO - Editing mode spa-eng.mode
[2019-09-06 04:56:18,311] {C:\Python37\lib\site-packages\apertium\installer.py:70} INFO - Editing mode spa-eng_US.mode
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 168, in translate
    deformatted = self._get_deformat(str(deformater), text)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 118, in _get_deformat
    proc_deformat = Popen(deformat, stdin=PIPE, stdout=PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>> exit()

Susha@Jacinth /cygdrive/c/Users/Susha
$ python3
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import apertium
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 168, in translate
    deformatted = self._get_deformat(str(deformater), text)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 118, in _get_deformat
    proc_deformat = Popen(deformat, stdin=PIPE, stdout=PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>>
```

**Comment by Vaydheesh** [comment]
Try calling `apertium.windows_update_path()`

**Comment by sushain97** [comment]
That doesn't seem to have helped:

```
$ python3
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import apertium
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 168, in translate
    deformatted = self._get_deformat(str(deformater), text)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 118, in _get_deformat
    proc_deformat = Popen(deformat, stdin=PIPE, stdout=PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>> apertium.windows_update_path()
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 168, in translate
    deformatted = self._get_deformat(str(deformater), text)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 118, in _get_deformat
    proc_deformat = Popen(deformat, stdin=PIPE, stdout=PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>> exit()

Susha@Jacinth /cygdrive/c/Users/Susha
$ python3
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import apertium
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 168, in translate
    deformatted = self._get_deformat(str(deformater), text)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 118, in _get_deformat
    proc_deformat = Popen(deformat, stdin=PIPE, stdout=PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>>
```

**Comment by Vaydheesh** [comment]
> Also what's the output of
> 
> ```
> os.environ['LOCALAPPDATA']
> os.environ['PATH']
> ```

and `os.pathsep`

**Comment by sushain97** [comment]
```
>>> os.environ['LOCALAPPDATA']
'C:\\Users\\Susha\\AppData\\Local'
>>> os.environ['PATH']
'C:\\Python37;C:\\Python37\\Scripts;C:\\Users\\Susha\\AppData\\Roaming\\Python\\Python36\\Scripts;C:\\Program Files (x86)\\Pandoc;C:\\Program \nFiles\\nodejs;C:\\Users\\Susha\\AppData\\Roaming\\npm;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36\\Scripts;C:\\cygwin64\\usr\\local\\bin;C:\\cygwin64\\bin;C:\\Program Files\\ConEmu\\ConEmu\\Scripts;C:\\Program Files\\ConEmu;C:\\Program Files\\ConEmu\\ConEmu;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Python37\\Scripts;C:\\Python37;C:\\Python27;C:\\Python27\\Scripts;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\WinSCP;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\PharosSystems\\Core;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64;C:\\Program Files (x86)\\SMLNJ\\bin;C:\\Program Files (x86)\\Pandoc;C:\\Program Files\\nodejs;C:\\ProgramData\\chocolatey\\bin;C:\\opscode\\chefdk\\bin;C:\\HashiCorp\\Vagrant\\bin;C:\\tools\\Java\\server-jre\\jdk1.8.0_192\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Users\\Susha\\.cargo\\bin;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36\\Scripts;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36-32;C:\\Users\\Susha\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Susha\\AppData\\Local\\atom\\bin;C:\\Users\\Susha\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\Microsoft VS Code\\bin;C:\\Users\\Susha\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Oracle\\VirtualBox;C:\\cygwin64\\lib\\lapack'
>>> os.pathsep
';'
```

**Comment by sushain97** [comment]
```
>>> apertium.windows_update_path()
>>> os.environ['PATH']
'C:\\Python37;C:\\Python37\\Scripts;C:\\Users\\Susha\\AppData\\Roaming\\Python\\Python36\\Scripts;C:\\Program Files (x86)\\Pandoc;C:\\Program \nFiles\\nodejs;C:\\Users\\Susha\\AppData\\Roaming\\npm;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36\\Scripts;C:\\cygwin64\\usr\\local\\bin;C:\\cygwin64\\bin;C:\\Program Files\\ConEmu\\ConEmu\\Scripts;C:\\Program Files\\ConEmu;C:\\Program Files\\ConEmu\\ConEmu;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Python37\\Scripts;C:\\Python37;C:\\Python27;C:\\Python27\\Scripts;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\WinSCP;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\PharosSystems\\Core;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64;C:\\Program Files (x86)\\SMLNJ\\bin;C:\\Program Files (x86)\\Pandoc;C:\\Program Files\\nodejs;C:\\ProgramData\\chocolatey\\bin;C:\\opscode\\chefdk\\bin;C:\\HashiCorp\\Vagrant\\bin;C:\\tools\\Java\\server-jre\\jdk1.8.0_192\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Users\\Susha\\.cargo\\bin;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36\\Scripts;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts;C:\\Users\\Susha\\AppData\\Local\\Programs\\Python\\Python36-32;C:\\Users\\Susha\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Susha\\AppData\\Local\\atom\\bin;C:\\Users\\Susha\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\Microsoft VS Code\\bin;C:\\Users\\Susha\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Oracle\\VirtualBox;C:\\cygwin64\\lib\\lapack'
```

**Comment by Vaydheesh** [comment]
Does this help?

```python
import os
import apertium


install_path = os.environ['LOCALAPPDATA']
current = os.environ['PATH']
apertium_bin_path = os.path.join(install_path, 'apertium-all-dev', 'bin')

print(os.path.isdir(apertium_bin_path))

update_path = '{}{}{}{}'.format(apertium_bin_path, os.pathsep, current, os.pathsep) 
os.environ['PATH'] = update_path

if 'apertium' not in os.environ['PATH']:
    os.environ['PATH'] = apertium_bin_path
```

**Comment by sushain97** [comment]
Nope:

```
>>> install_path = os.environ['LOCALAPPDATA']
>>> current = os.environ['PATH']
>>> apertium_bin_path = os.path.join(install_path, 'apertium-all-dev', 'bin')
>>> print(os.path.isdir(apertium_bin_path))
False
>>> update_path = '{}{}{}{}'.format(apertium_bin_path, os.pathsep, current, os.pathsep)
>>> os.environ['PATH'] = update_path
>>> if 'apertium' not in os.environ['PATH']:     os.environ['PATH'] = apertium_bin_path
...
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 168, in translate
    deformatted = self._get_deformat(str(deformater), text)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 118, in _get_deformat
    proc_deformat = Popen(deformat, stdin=PIPE, stdout=PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Here's the whole directory:

```
$ ls -R AppData/Local/apertium-all-dev/
AppData/Local/apertium-all-dev/:
share

AppData/Local/apertium-all-dev/share:
apertium

AppData/Local/apertium-all-dev/share/apertium:
apertium-eng-spa  modes

AppData/Local/apertium-all-dev/share/apertium/apertium-eng-spa:
apertium-eng-spa.eng-spa.genitive.t1x  eng-spa.autobil.bin   eng-spa.t1x.bin       spa-eng.autopgen.bin
apertium-eng-spa.eng-spa.t1x           eng-spa.autogen.bin   eng-spa.t2x.bin       spa-eng.prob
apertium-eng-spa.eng-spa.t2x           eng-spa.autolex.bin   eng-spa.t3x.bin       spa-eng.t1x.bin
apertium-eng-spa.eng-spa.t3x           eng-spa.automorf.bin  spa-eng.autobil.bin   spa-eng.t2x.bin
apertium-eng-spa.spa-eng.t1x           eng-spa.autopgen.bin  spa-eng.autogen.bin   spa-eng.t3x.bin
apertium-eng-spa.spa-eng.t2x           eng-spa.genitive.bin  spa-eng.autolex.bin   spa-eng_US.autogen.bin
apertium-eng-spa.spa-eng.t3x           eng-spa.prob          spa-eng.automorf.bin

AppData/Local/apertium-all-dev/share/apertium/modes:
eng-spa.mode  spa-eng.mode  spa-eng_US.mode
```

**Comment by sushain97** [comment]
This seems to have worked though:

```
>>> apertium.installer.install_apertium()
[2019-09-07 05:45:03,473] {C:\Python37\lib\site-packages\apertium\installer.py:31} INFO - http://apertium.projectjj.com//win64/nightly/apertium-all-dev.zip -> apertium-all-dev.zip download completed
[2019-09-07 05:45:10,063] {C:\Python37\lib\site-packages\apertium\installer.py:36} INFO - apertium-all-dev.zip Extraction completed
[2019-09-07 05:45:10,068] {C:\Python37\lib\site-packages\apertium\installer.py:38} INFO - apertium-all-dev.zip removed
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 187, in translate
    return translator.translate(text, mark_unknown, formatting, deformat, reformat)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 168, in translate
    deformatted = self._get_deformat(str(deformater), text)
  File "C:\Python37\lib\site-packages\apertium\translation\__init__.py", line 118, in _get_deformat
    proc_deformat = Popen(deformat, stdin=PIPE, stdout=PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>> exit()

Susha@Jacinth /cygdrive/c/Users/Susha
$ python3
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> apertium.translate('en', 'es', 'house')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'apertium' is not defined
>>> import apertium
>>> apertium.translate('en', 'es', 'house')
[2019-09-07 05:45:35,561] {C:\Python37\lib\site-packages\apertium\utils.py:173} WARNING - Calling subprocess lt-proc
[2019-09-07 05:45:35,674] {C:\Python37\lib\site-packages\apertium\utils.py:173} WARNING - Calling subprocess apertium-tagger
[2019-09-07 05:45:35,732] {C:\Python37\lib\site-packages\apertium\utils.py:173} WARNING - Calling subprocess apertium-pretransfer
[2019-09-07 05:45:35,785] {C:\Python37\lib\site-packages\apertium\utils.py:173} WARNING - Calling subprocess apertium-transfer
[2019-09-07 05:45:35,850] {C:\Python37\lib\site-packages\apertium\utils.py:173} WARNING - Calling subprocess lt-proc
[2019-09-07 05:45:35,958] {C:\Python37\lib\site-packages\apertium\utils.py:173} WARNING - Calling subprocess lrx-proc
```

It looks like the wrappers aren't being installed after pip install?

**Comment by Vaydheesh** [comment]
> It looks like the wrappers aren't being installed after pip install?

Yes, pip installation doesn't install apertium binaries

1. windows https://ci.appveyor.com/project/apertium/apertium-python/builds/27252435/job/i5pdx5ydjs6ssl9i#L42
2. ubuntu https://travis-ci.com/apertium/apertium-python/jobs/232072956#L203

Can we use something like `apertium.download()` which would call https://github.com/apertium/apertium-python/blob/master/setup.py#L21-L29, similar to nltk https://www.nltk.org/data.html#interactive-installer

**Comment by sushain97** [comment]
What... it should have been per https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools ?

Is the output showing an error that gets silenced or something? Maybe https://stackoverflow.com/questions/44549600/custom-post-install-script-not-running-with-pip will help.

**Comment by Vaydheesh** [comment]
> Is the output showing an error that gets silenced or something?

`PostInstallCommand` isn't executed during pip install

- https://travis-ci.com/apertium/apertium-python/jobs/232113355#L204
- https://ci.appveyor.com/project/apertium/apertium-python/builds/27257998/job/k6ceqt70mhvsri5e#L42

installation from source with `-e` flag https://stackoverflow.com/questions/44549600/custom-post-install-script-not-running-with-pip/45389836#45389836 is working fine

- https://travis-ci.com/apertium/apertium-python/jobs/232114376#L204
- appveyor build is waiting for input, since the target directory already exists https://ci.appveyor.com/project/apertium/apertium-python/builds/27258121/job/hybalu83b3pcxp5b#L53

**Comment by Vaydheesh** [comment]
seems like we need to handle multiple cases https://stackoverflow.com/questions/19569557/pip-not-picking-up-a-custom-install-cmdclass/45021666#45021666

can you `test-release` the `test_build` branch

**Comment by sushain97** [comment]
Hmm.. that's weird. I can do the test-release.

Also, you can look into nltk/scipy/numpy and see how do they stuff.

**Comment by sushain97** [comment]
#69 makes this really annoying... also, now I get the install step happening multiple times on release.

Anyway test released to 0.2.1: https://test.pypi.org/project/apertium/

**Comment by sushain97** [comment]
(feel free to just test-release yourself to any random project on pypi)

**Comment by Vaydheesh** [comment]
https://travis-ci.com/apertium/apertium-python/builds/126366333

the updated `setup.py` is working fine with pip install

**Comment by sushain97** [comment]
Does it install multiple times?

**Comment by Vaydheesh** [comment]
No,

the files are copied only once, https://travis-ci.com/apertium/apertium-python/jobs/232164599#L540
and `Collecting apertium` is also executed once https://travis-ci.com/apertium/apertium-python/jobs/232164599#L210

**Comment by sushain97** [comment]
Cool. Send over a PR?

**Comment by Vaydheesh** [comment]
`pip install apertium` is now calling setup.py
https://ci.appveyor.com/project/Vaydheesh/apertium-python/builds/27407280/job/i6qn9k2h5j5sc42r#L48

does this solve the issue you've been facing?

**Comment by sushain97** [comment]
Yep! It works now. Awesome! Sorry for the late reply.

Two notes:
1. It would be nice to display progress while `setup.py install` is running during `pip install`.
2. These logs are too much for a prod user:
```
>>> import apertium
>>> apertium.analyze('eng', 'cats')
[2019-10-02 05:57:55,877] {C:\Python37\lib\site-packages\apertium\utils.py:173} WARNING - Calling subprocess lt-proc
[cats/cat<n><pl>]
```
