### ISSUE TITLE
Generation isn't consistent with apertium CLI and breaks

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-python#9]
Currently, some of these break and they're not consistent with the CLI.

- [ ] remove SEPARATOR code that I don't think is useful here
- [ ] perform as below
- [ ] tests for each of those cases

```
[84378:84376 - 0:522] 10:45:50 [Sushain@zircon.lan:o +1] ~/Documents/apertium-python
$ echo 'cat<n><pl>' | apertium eng-gener -f none
cat<n><pl>

[84378:84376 - 0:523] 10:45:54 [Sushain@zircon.lan:o +1] ~/Documents/apertium-python
$ echo '^cat<n><pl>$' | apertium eng-gener -f none
cats

[84378:84376 - 0:524] 10:45:58 [Sushain@zircon.lan:o +1] ~/Documents/apertium-python
$ echo '^cat<n><pl>$ ^cat<n><pl>$' | apertium eng-gener -f none
cats cats

[84378:84376 - 0:525] 10:46:02 [Sushain@zircon.lan:o +1] ~/Documents/apertium-python
$ python3
Python 3.6.4 (default, Mar  9 2018, 23:15:08)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from apertium import generate
>>> generate('cat<n><pl>') == 'cat<n><pl>'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: generate() missing 1 required positional argument: 'lang'
>>> generate('cat<n><pl>', 'en') == 'cat<n><pl>'
False
>>> generate('^cat<n><pl>$', 'en') == 'cats'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Sushain/Documents/apertium-python/apertium/generation/__init__.py", line 30, in generate
    lexical_units, to_generate = preproc_text(in_text)
  File "/Users/Sushain/Documents/apertium-python/apertium/generation/__init__.py", line 15, in preproc_text
    return lexical_units, SEPARATOR.join(lexical_units)
UnboundLocalError: local variable 'lexical_units' referenced before assignment
>>> generate('^cat<n><pl>$ ^cat<n><pl>$', 'en') == 'cats cats'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Sushain/Documents/apertium-python/apertium/generation/__init__.py", line 30, in generate
    lexical_units, to_generate = preproc_text(in_text)
  File "/Users/Sushain/Documents/apertium-python/apertium/generation/__init__.py", line 15, in preproc_text
    return lexical_units, SEPARATOR.join(lexical_units)
UnboundLocalError: local variable 'lexical_units' referenced before assignment
```

**Comment by sushain97** [comment]
@arghyatiger I think this is most important and should be fixed first.

**Comment by arghyatiger** [comment]
@sushain97  Ohh, this is bad. :/  I'll fix this first

**Comment by sushain97** [comment]
As I said on the original PR, you need to make branches like issue-9 from
master and make PRs from those. I'm not looking through a 60 commit diff
that includes all of the old stuff :)
